# **Assignment 1**

## **Part 1:**

In [51]:
import pandas as pd
import numpy as np

## **Load the DataSet:**

In [54]:
from google.colab import files
uploaded  = files.upload()

Saving california_housing_train (1).csv to california_housing_train (1).csv

In [55]:
df = pd.read_csv('california_housing_train (1).csv')
df.info() #gives info regarding each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

## **Display the first 5 and last 10 rows of the data:**

In [56]:
df.head(5) #displaying the first five rows of the data using the head method

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [57]:
df.tail(10)      #displaying the last 10 rows of the data using the tail method

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16990,-124.22,41.73,28.0,3003.0,699.0,1530.0,653.0,1.7038,78300.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16992,-124.23,40.81,52.0,1112.0,209.0,544.0,172.0,3.3462,50800.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

## **Data Summary:**

In [58]:
df.dtypes        #generating the different data types along each column

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [59]:
df.describe()               #generate a statistical summary of each column

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [60]:
unique_total_bed = df.total_bedrooms.unique()                    #create an array of all the unique elements in the total_bedrooms column
print(unique_total_bed)
print(len(unique_total_bed))

[1283. 1901.  174. ... 1637. 1308.  936.]
1848

## **Data Transformation:**

In [61]:
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms']/df['total_rooms']      #creating a new column
print(df['total_bedrooms_per_total_rooms'])
print(df['total_bedrooms_per_total_rooms'].mean())                                 #print the mean of the new column
print(df['total_bedrooms_per_total_rooms'].std())                                  #print the std deviation of the new column

0        0.228617
1        0.248497
2        0.241667
3        0.224517
4        0.224209
           ...
16995    0.177718
16996    0.224777
16997    0.198356
16998    0.206587
16999    0.164835
Name: total_bedrooms_per_total_rooms, Length: 17000, dtype: float64
0.21275998821034803
0.057823008903161756

## **Data Filtering:**

In [62]:
df[df['median_income'] > 5]                     #display all the rows which have median_income greater than 5

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_bedrooms_per_total_rooms
32,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0,0.172535
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0,0.161077
92,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0,0.153194
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0,0.165998
100,-115.59,32.79,8.0,2183.0,307.0,1000.0,287.0,6.3814,159900.0,0.140632
...,...,...,...,...,...,...,...,...,...,...
16737,-122.89,38.38,16.0,2017.0,369.0,931.0,336.0,5.7664,267500.0,0.182945
16762,-122.94,38.57,33.0,1530.0,266.0,728.0,250.0,5.1005,266700.0,0.173856
16776,-123.00,38.33,8.0,3223.0,637.0,851.0,418.0,5.6445,364800.0,0.197642
16802,-123.17,39.18,14.0,2240.0,327.0,1030.0,308.0,5.9585,214900.0,0.145982
16899,-124.05,40.94,14.0,1452.0,217.0,516.0,181.0,5.0329,165600.0,0.149449

In [63]:
median_greater_than_5 = df[df['median_income'] > 5].index.to_numpy()            #create an array of all the values in median_income which are greater than 5
print(median_greater_than_5)

[   32    69    92 ... 16776 16802 16899]

In [64]:
new_df = df[(df['total_rooms'] > 10000) & (df['median_house_value'] < 150000)]          #display all the rows which satisfy total rooms greater than 10,000 and median_house_value less than 150,000
new_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_bedrooms_per_total_rooms
133,-116.06,34.15,15.0,10377.0,2331.0,4507.0,1807.0,2.2466,66800.0,0.224631
191,-116.36,33.88,11.0,12557.0,3098.0,2453.0,1232.0,1.7844,78500.0,0.246715
198,-116.38,33.73,10.0,11836.0,2405.0,3811.0,1570.0,4.0079,134500.0,0.203194
201,-116.39,33.82,15.0,11115.0,2257.0,4122.0,1653.0,2.7219,74400.0,0.203059
229,-116.47,33.81,7.0,10105.0,2481.0,6274.0,2095.0,2.4497,90900.0,0.245522
...,...,...,...,...,...,...,...,...,...,...
12654,-121.75,38.67,9.0,12139.0,2640.0,6837.0,2358.0,3.1250,132500.0,0.217481
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0,0.197536
13388,-121.94,38.27,35.0,10869.0,2226.0,9879.0,2152.0,2.5681,81300.0,0.204803
13707,-122.00,38.25,7.0,11768.0,1893.0,6657.0,1874.0,4.9222,142900.0,0.160860
15436,-122.31,40.55,11.0,13714.0,2302.0,6511.0,2267.0,3.5522,100100.0,0.167858

## **Export Modified Data:**

In [65]:
df.to_csv('modif_cal_housing_train.csv', index=False)                   #saving the modified dataframe to a new .csv file

## **Part 2:**

In [36]:
import numpy as np

## **Array Creation and Indexing:**

In [37]:
arr = np.arange(1, 21, 1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
arr_2 = arr[1::2]         #generating new array by slicing AND using steps
arr_2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
arr_3 = np.random.randint(10, 100, (5, 4))              #generating a random matrix of size 5 x 4 using random.randint function
arr_3

array([[27, 81, 76, 12],
       [29, 27, 96, 38],
       [59, 19, 54, 23],
       [87, 35, 57, 88],
       [19, 50, 85, 72]])

In [40]:
arr_4 = arr_3[:4, :3]            #slicing till the 4th row and 3rd column
arr_4

array([[27, 81, 76],
       [29, 27, 96],
       [59, 19, 54],
       [87, 35, 57]])

## **Array Manipulation:**

In [41]:
arr = arr.reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
mult_arr = arr @ arr_3
mult_arr

array([[ 705,  582, 1083,  869],
       [1810, 1642, 2923, 2034],
       [2915, 2702, 4763, 3199],
       [4020, 3762, 6603, 4364]])

## **Boolean and Fancy Indexing:**

In [44]:
arr_5 = np.random.randint(0, 100, 50)
arr_5

array([25,  1, 78, 92, 49, 63, 23, 71,  2, 43,  9, 93,  5, 77, 81, 40, 95,
       14, 81, 93, 88, 58, 98, 95, 48, 97, 94, 92, 15, 31, 64, 32, 39, 14,
       58, 40, 22,  1, 32, 89,  4, 91,  3, 32, 84, 13, 52, 64, 98, 50])

In [45]:
b = arr_5 > 50            #boolean masking on arr_5
arr_5[b]

array([78, 92, 63, 71, 93, 77, 81, 95, 81, 93, 88, 58, 98, 95, 97, 94, 92,
       64, 58, 89, 91, 84, 52, 64, 98])

In [46]:
#finding all the elements at square-number indices
c = np.arange(7)**2
arr_5[c]

array([25,  1, 49, 43, 95, 97, 22])

## **Statistical Operations:**

In [47]:
#using mult_arr from earlier matrix multiplication
#axis = 0 for columns
mean = np.mean(mult_arr, axis = 0)
print(mean)
max = np.max(mult_arr, axis = 0)
print(max)
summation = np.sum(mult_arr, axis = 0)
print(summation)

[2362.5 2172.  3843.  2616.5]
[4020 3762 6603 4364]
[ 9450  8688 15372 10466]

In [49]:
mask = mult_arr > mean                                                          #boolean mask on mult_arr
filter_mult_arr = mult_arr[mask]                                                #gives an array of elements which are greater than their column_mean, the elements are selected row-wise
print(filter_mult_arr)

[2915 2702 4763 3199 4020 3762 6603 4364]

# **Part 3:**

## **Fibonacci Numbers**

In [38]:
arr_fibb = [0] * 100                #creating an array of 100 elements each initialized to 0
arr_fibb[0] = 1
arr_fibb[1] = 1
for count in range(2, 100):
  arr_fibb[count] = arr_fibb[count - 1] + arr_fibb[count - 2]

print(arr_fibb)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135, 308061521170129, 498454011879264, 806515533049393, 1304969544928657, 2111485077978050, 3416454622906707, 5527939700884757, 8944394323791464, 14472334024676221, 23416728348467685, 37889062373143906, 61305790721611591, 99194853094755497, 160500643816367088, 259695496911122585, 420196140727489673, 679891637638612258, 1100087778366101931, 1779979416004714189, 2880067194370816120, 4660046610375530309, 7540113804746346429, 12200160415121876738, 19740274219868223167, 31940434634990099905, 51680708854858323072, 83621143489848422977, 135301852344706746049, 218922995834555169026, 354224848179261915075]

## **Looping Through Numbers:**

In [42]:
new_arr = np.arange(1, 51, 1)
for r in range (0, 50):
  if((new_arr[r]%3 == 0) & (new_arr[r]%5 != 0) ):              #when number is divisible by ONLY 3
    print("Fizz")
  elif((new_arr[r]%3 != 0) & (new_arr[r]%5 == 0) ):            #when number is divisible by ONLY 5
    print("Buzz")
  elif((new_arr[r]%3 == 0) & (new_arr[r]%5 == 0) ):            #when number is divisible by 3 AND 5
    print("FizzBuzz")
  else:                         #when number is not divisible by both 3 and 5
    print("LMAO")

LMAO
LMAO
Fizz
LMAO
Buzz
Fizz
LMAO
LMAO
Fizz
Buzz
LMAO
Fizz
LMAO
LMAO
FizzBuzz
LMAO
LMAO
Fizz
LMAO
Buzz
Fizz
LMAO
LMAO
Fizz
Buzz
LMAO
Fizz
LMAO
LMAO
FizzBuzz
LMAO
LMAO
Fizz
LMAO
Buzz
Fizz
LMAO
LMAO
Fizz
Buzz
LMAO
Fizz
LMAO
LMAO
FizzBuzz
LMAO
LMAO
Fizz
LMAO
Buzz

## **Variable-Length Arguments:**

In [49]:
def median(list):
  median = 0;     #using median as 0 if the length of the list provided is 0
  list.sort()
  n = len(list)
  if(n > 0):
   if(n%2 == 0):
    median = (list[(n-1)//2] + list[((n-1)//2) + 1])/2            #median formula for even-length list
   elif(n%2 != 0):
    median = list[n//2]                                           #median formula for odd-length list
  return median

In [51]:
numbers = np.random.randint(1, 10, 6)
print(numbers)
numb_list = numbers.tolist()
print(median(numb_list))

[9 2 4 6 5 8]
5.5

In [4]:
def average(lst):
    total = sum(lst)
    length = len(lst)
    if (length == 0):              #checking the "division by zero" case with if-else statements
        return "No Input Given"
    else:
        avg = total / length
        return avg

In [7]:
user_input = input("Enter numbers: ")

numbers = list(map(int, user_input.split())) #taking user input as a string and converting it into a list using split() method

avg = average(numbers)
print(avg)

Enter numbers: 1 2 3 4 5
3.0

## **Error Handling:**

In [6]:
#take the above example of calculating average
user_input_2 = input("Enter NO Number: ")
numbers_2 = list(map(int, user_input_2.split()))
avg_zero = average(numbers_2)
print(avg_zero)

Enter NO Number:
No Input Given

## **Part - 4**

In [9]:
import numpy as np

In [24]:
random = np.random.randint(1, 10, (2, 3, 4)) #generate random array of dimensions 2 x 3 x 4
random

array([[[2, 2, 8, 6],
        [4, 8, 3, 3],
        [2, 5, 6, 3]],

       [[7, 7, 4, 1],
        [4, 7, 8, 1],
        [4, 2, 4, 9]]])

In [28]:
#reshaping the array
random = random.reshape(( 3, 4, 2 ))
random

array([[[2, 2],
        [8, 6],
        [4, 8],
        [3, 3]],

       [[2, 5],
        [6, 3],
        [7, 7],
        [4, 1]],

       [[4, 7],
        [8, 1],
        [4, 2],
        [4, 9]]])

In [30]:
random_sum = np.sum(random, axis = 0) #sum along the depth
random_sum

array([[ 8, 14],
       [22, 10],
       [15, 17],
       [11, 13]])

In [32]:
rand_2 = np.random.randint(1, 50, (2, 4)) #generate random array of dimensions 2 x 4
rand_2

array([[35, 21, 18,  2],
       [37,  1,  3, 24]])

In [33]:
vector = np.array([1, 2, 3 ,4])

In [34]:
rand_2 = rand_2 + vector #vector addition to each row
rand_2

array([[36, 23, 21,  6],
       [38,  3,  6, 28]])